version: "3.9"

services:
  router:
    build: 
      context: .
      dockerfile: Dockerfile_router
    image: image-router:latest
    container_name: alpine-router  
    volumes:
      - ./alpine:/exchange:rw

  gui:
    build: 
      context: .
      dockerfile: Dockerfile_gui
    image: image-gui:latest	
    container_name: alpine-gui
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
  